### ISSUE TITLE
New nuxt project throws error: ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by agnelnieves** [nuxt/nuxtjs.org#1268]
This happens when using:

```
npm init nuxt-app <project-name>
or
npx create-nuxt-app <project-name>
or 
yarn create nuxt-app <project-name>
```

Doesn't let me serve either.

Details:

OS: Mac OS 10.15.7
Node: v11.10.1

**Comment by agnelnieves** [comment]
Was able to nail it down a bit. Issue happens only if I enable  stylelint when creating a project.

**Comment by agnelnieves** [comment]
Now I'm getting:
```
yarn install v1.16.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

/Users/agneln/.npm/_npx/ea7c6e7510ea3309/node_modules/sao/lib/installPackages.js:108
        throw new SAOError(`Failed to install ${packageName} in ${cwd}`)
        ^

Error: Failed to install packages in /Users/agneln/Documents/veoveo
    at ChildProcess.ps.on.code (/Users/agneln/.npm/_npx/ea7c6e7510ea3309/node_modules/sao/lib/installPackages.js:108:15)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
    
```

**Comment by agnelnieves** [comment]
Shoot, thanks @danielroe. Can confirm this was indeed my problem. Using NVM gotta make 12.x the default version, will close this thread.

**Comment by typeoneerror** [comment]
@danielroe how about with Node 16?

```
[Edea] ~/Dev/typeoneerror/typeoneerror (main) $ nvm use
Found '/Users/typeoneerror/Dev/typeoneerror/typeoneerror/.nvmrc' with version <lts/gallium>
Now using node v16.15.1 (npm v8.11.0)
[Edea] ~/Dev/typeoneerror/typeoneerror (main) $ yarn generate
yarn run v1.22.10
$ nuxt generate
Nuxt CLI v3.0.0-rc.8                                                                                                 10:09:40
ℹ Using default Tailwind CSS file from runtime/tailwind.css                                         nuxt:tailwindcss 10:09:45
ℹ Client built in 2903ms                                                                                             10:09:48
ℹ Building server...                                                                                                 10:09:48
✔ Server built in 947ms                                                                                              10:09:49
✔ Generated public .output/public                                                                              nitro 10:09:49
ℹ Initializing prerenderer                                                                                     nitro 10:09:49
ℹ Prerendering 1 initial routes with crawler                                                                   nitro 10:09:55

 ERROR  globalThis.__buildAssetsURL is not a function                                                                10:09:55

  at .nuxt/prerender/chunks/app/_nuxt/index.19d031bf.mjs:21:36
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async .nuxt/prerender/chunks/app/server.mjs:7150:7
  at async Object.callAsync (node_modules/@nuxt/kit/node_modules/unctx/dist/index.mjs:53:16)
  at async applyPlugin (.nuxt/prerender/chunks/app/server.mjs:3600:23)
  at async applyPlugins (.nuxt/prerender/chunks/app/server.mjs:3609:5)
  at async createNuxtAppServer (.nuxt/prerender/chunks/app/server.mjs:7473:7)
  at async Object.renderToString (.nuxt/prerender/chunks/renderer.mjs:270:19)
```
