### ISSUE TITLE
Manual installation instructions not working

### ISSUE THREAD

**Issue by NickSto** [nuxt/nuxtjs.org#1284]
Hi, I wanted to try out the manual installation described [here](https://nuxtjs.org/docs/2.x/get-started/installation), but I got an error at the end instead of a "Hello world!". I think I followed the instructions exactly, but sorry if I missed something.

I'm assuming the instructions are out of sync with the current version of nuxt? I'm pretty new to frontend so I'm not sure what's missing.

## Step to reproduce
```
mkdir nuxthub
cd nuxthub
printf '{
  "name": "my-app",
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "generate": "nuxt generate",
    "start": "nuxt start"
  }
}' > package.json
npm install nuxt
mkdir pages
printf '<template>
  <h1>Hello world!</h1>
</template>' > pages/index.vue
npm run dev
```
FYI, I got the same result when using the yarn instructions.

## Result
I opened http://localhost:3000/ and got an error page instead of the "Hello world!" page I created.

Here is the stack trace from the terminal:
```
 ERROR  in ./.nuxt/client.js                                              friendly-errors 18:42:14

Module build failed (from ./node_modules/babel-loader/lib/index.js):      friendly-errors 18:42:14
Error: /home/me/code/nuxthub/.nuxt/client.js: Cannot find module '@babel/preset-env/lib/utils'
Require stack:
- /home/me/code/nuxthub/node_modules/@nuxt/babel-preset-app/src/polyfills-plugin.js
- /home/me/code/nuxthub/node_modules/@nuxt/babel-preset-app/src/index.js
- /home/me/code/nuxthub/node_modules/@babel/core/lib/config/files/module-types.js
- /home/me/code/nuxthub/node_modules/@babel/core/lib/config/files/configuration.js
- /home/me/code/nuxthub/node_modules/@babel/core/lib/config/files/index.js
- /home/me/code/nuxthub/node_modules/@babel/core/lib/index.js
- /home/me/code/nuxthub/node_modules/babel-loader/lib/index.js
- /home/me/code/nuxthub/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js
- /home/me/code/nuxthub/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js
- /home/me/code/nuxthub/node_modules/webpack/lib/NormalModule.js
- /home/me/code/nuxthub/node_modules/webpack/lib/NormalModuleFactory.js
- /home/me/code/nuxthub/node_modules/webpack/lib/Compiler.js
- /home/me/code/nuxthub/node_modules/webpack/lib/webpack.js
- /home/me/code/nuxthub/node_modules/@nuxt/webpack/dist/webpack.js
- /home/me/code/nuxthub/node_modules/@nuxt/builder/dist/builder.js
- /home/me/code/nuxthub/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at n (/home/me/code/nuxthub/node_modules/jiti/dist/v8cache.js:2:2364)
    at PluginPass.Program (/home/me/code/nuxthub/node_modules/@nuxt/babel-preset-app/src/polyfills-plugin.js:15:34)
    at newFn (/home/me/code/nuxthub/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (/home/me/code/nuxthub/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/me/code/nuxthub/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/home/me/code/nuxthub/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/home/me/code/nuxthub/node_modules/@babel/traverse/lib/context.js:116:16)
    at TraversalContext.visitSingle (/home/me/code/nuxthub/node_modules/@babel/traverse/lib/context.js:85:19)
    at TraversalContext.visit (/home/me/code/nuxthub/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/home/me/code/nuxthub/node_modules/@babel/traverse/lib/index.js:82:17)
    at traverse (/home/me/code/nuxthub/node_modules/@babel/traverse/lib/index.js:62:12)
    at transformFile (/home/me/code/nuxthub/node_modules/@babel/core/lib/transformation/index.js:107:29)
    at transformFile.next (<anonymous>)
                                                                          friendly-errors 18:42:14
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
                                                                          friendly-errors 18:42:14
```

## Environment
OS: Ubuntu 20.04
npm: 7.5.4
nuxt: 2.15.1

(and here's my full [package-lock.json](https://github.com/nuxt/nuxtjs.org/files/6025992/package-lock.json.gz))

**Comment by NickSto** [comment]
@danielroe Cool, thanks so much for the pointer! I tried again with the latest version and it's fixed.
