### ISSUE TITLE
error generate

### ISSUE THREAD

**Issue by didaputraa** [nuxt/nuxtjs.org#2112]
node version: 16.15.0 
run generate

```WARN  [@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.```
```
ERROR in ./node_modules/@docus/theme/dist/components/atoms/CodeGroup.vue?vue&type=style&index=0&id=8815edb8&prod&scoped=true&lang=postcss& (./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??ref--4-oneOf-1-2!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@docus/theme/dist/components/atoms/CodeGroup.vue?vue&type=style&index=0&id=8815edb8&prod&scoped=true&lang=postcss&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/stylePostLoader.js):
TypeError: Cannot read properties of undefined (reading 'spaces')
    at D:\tutor\nuxtjs.org\node_modules\@docus\theme\dist\components\atoms\CodeGroup.vue:1:95
    at rewriteSelector (D:\tutor\nuxtjs.org\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17607:24)
    at D:\tutor\nuxtjs.org\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17520:13
    at Root.each (D:\tutor\nuxtjs.org\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:13998:17)
    at Processor.func (D:\tutor\nuxtjs.org\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17519:22)
    at Processor._runSync (D:\tutor\nuxtjs.org\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17122:27)
    at Processor.processSync (D:\tutor\nuxtjs.org\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17217:24)
    at processRule (D:\tutor\nuxtjs.org\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17522:8)
    at Rule (D:\tutor\nuxtjs.org\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17464:13)
    at LazyResult.visitSync (D:\tutor\nuxtjs.org\node_modules\postcss\lib\lazy-result.js:308:19)
    at LazyResult.walkSync (D:\tutor\nuxtjs.org\node_modules\postcss\lib\lazy-result.js:297:20)
    at D:\tutor\nuxtjs.org\node_modules\postcss\lib\lazy-result.js:291:39
    at Rule.each (D:\tutor\nuxtjs.org\node_modules\postcss\lib\container.js:41:16)
    at LazyResult.walkSync (D:\tutor\nuxtjs.org\node_modules\postcss\lib\lazy-result.js:290:16)
    at D:\tutor\nuxtjs.org\node_modules\postcss\lib\lazy-result.js:291:39
    at Root.each (D:\tutor\nuxtjs.org\node_modules\postcss\lib\container.js:41:16)
    at LazyResult.walkSync (D:\tutor\nuxtjs.org\node_modules\postcss\lib\lazy-result.js:290:16)
 @ ./node_modules/@docus/theme/dist/components/atoms/CodeGroup.vue?vue&type=style&index=0&id=8815edb8&prod&scoped=true&lang=postcss& (./node_modules/vue-style-loader??ref--4-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??ref--4-oneOf-1-2!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@docus/theme/dist/components/atoms/CodeGroup.vue?vue&type=style&index=0&id=8815edb8&prod&scoped=true&lang=postcss&) 4:14-397
 @ ./node_modules/@docus/theme/dist/components/atoms/CodeGroup.vue?vue&type=style&index=0&id=8815edb8&prod&scoped=true&lang=postcss&
 @ ./node_modules/@docus/theme/dist/components/atoms/CodeGroup.vue
 @ ./node_modules/.cache/nuxt/components/index.js
 @ ./node_modules/.cache/nuxt/components/plugin.js
 @ ./node_modules/.cache/nuxt/index.js
 @ ./node_modules/.cache/nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/.cache/nuxt/composition-api/register.js ./node_modules/.cache/nuxt/client.js

 FATAL  Nuxt build error                                                                                      21:36:43

  at WebpackBundler.webpackCompile (node_modules\@nuxt\webpack\dist\webpack.js:2127:21)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async WebpackBundler.build (node_modules\@nuxt\webpack\dist\webpack.js:2076:5)
  at async Builder.build (node_modules\@nuxt\builder\dist\builder.js:327:5)
  at async ensureBuild (node_modules\@nuxt\cli\dist\cli-generate.js:145:3)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-generate.js:283:7)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:413:7)```

**Comment by rishi-raj-jain** [comment]
@didaputraa Can you create a reproduction and link it here after upgrading to the latest version?
