### ISSUE TITLE
Can't run the development server with yarn dev

### ISSUE THREAD

**Issue by MatCast** [nuxt/nuxtjs.org#801]
After cloning the repo and cd into the repo folder if i run `yarn dev` i get an errorr:
```
/bin/sh: 1: nuxt: not found
error Command failed with exit code 127.
```
If i  run `yarn add nuxt` and then `yarn dev` i get:
```
FATAL  Both nuxt and nuxt-edge dependencies are installed! This is unsupported, please choose one and remove the other one from dependencies.

  at Object.run (node_modules/@nuxt/cli-edge/dist/cli-index.js:3025:11)
  at Object.<anonymous> (node_modules/nuxt-edge/bin/nuxt.js:4:31)
  at Module._compile (internal/modules/cjs/loader.js:1137:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
  at Module.load (internal/modules/cjs/loader.js:985:32)
  at Function.Module._load (internal/modules/cjs/loader.js:878:14)
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
  at internal/main/run_main_module.js:17:47

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MatCast** [comment]
Ok i solved the problem as  i didnt run `yarn` after `cd nuxtjs.org`.
